---

compression:
  level: 5
  format: 7z
  extension: 7z

backup: true
encrypted: true
hash: true
test-archive: false
clear-recent: false

extensions:
  - aac
  - bmp
  - flac
  - gif
  - jpeg
  - jpe
  - jpg
  - m4a
  - mkv
  - mpeg
  - mpg
  - mp3
  - mp4
  - ogg
  - opus
  - png
  - svg
  - tif
  - tiff
  - webm
  - webp
  - wmv

rename-extensions:
  jpe: jpeg
  jpg: jpeg
  mpg: mpeg
  tif: tiff

skip-extensions:
  - json
  - yaml

ignore-files:
  - .ignore
  - _ignore

archive-dir: /path/where/you/store/archives
extract-dir: .
hash-algorithm: sha224
data-dir: .darch

use-trash: false
ask-confirmation: true
always-yes: false
dry-run: false
